sudo: required
dist: trusty
language: c
osx_image: xcode8
matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang
script:
  - npm run dist
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"